services:
  php_server:
    build: .
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql_sgbd

  mysql_sgbd:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: testdb
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin_ui:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql_sgbd
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "8081:80"

volumes:
  mysql_data:
